# Generated by Django 3.1.4 on 2020-12-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipments',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('shipper_company_id', models.IntegerField()),
                ('carrier_company_id', models.IntegerField()),
                ('truck_id', models.IntegerField()),
                ('co2_model_id', models.IntegerField()),
                ('travelled_distance', models.DecimalField(decimal_places=2, max_digits=19)),
                ('fuel_consumed', models.DecimalField(decimal_places=2, max_digits=19)),
                ('estimated_fuel_consumed', models.DecimalField(decimal_places=2, max_digits=19)),
                ('weight', models.DecimalField(decimal_places=10, max_digits=19)),
                ('type_of_goods', models.CharField(max_length=128)),
                ('start_country', models.CharField(max_length=128)),
                ('start_city', models.CharField(max_length=128)),
                ('start_postcode', models.CharField(max_length=128)),
                ('end_country', models.CharField(max_length=128)),
                ('end_city', models.CharField(max_length=128)),
                ('end_postcode', models.CharField(max_length=128)),
                ('type_of_calculations', models.CharField(max_length=128)),
                ('allocated_distance', models.DecimalField(decimal_places=2, max_digits=19)),
                ('allocated_fuel', models.DecimalField(decimal_places=2, max_digits=19)),
                ('total_co2_emitted', models.DecimalField(decimal_places=2, max_digits=19)),
                ('creation_timestamp', models.DateTimeField()),
                ('last_updated_timestamp', models.DateTimeField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('fuel_type', models.CharField(max_length=64)),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
