# Generated by Django 3.1.4 on 2020-12-05 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0002_auto_20201204_1908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipments',
            options={'managed': False},
        ),
    ]
